apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-demo-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/arifrhm/ocp-portfolio-project.git'
    path: '04-microservices/overlays/production'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
