apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineSnapshot
metadata:
  name: test-vm-cirros-snapshot
  namespace: kubevirt-workloads
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: test-vm-cirros
