apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay deploys the base app into the 'production' namespace
namespace: production

resources:
  - ../../

patches:
  - path: replica-patch.yaml
